// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Result.proto

package googleprotobuf_json;

public final class ResultProto {
  private ResultProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CourseMarksOrBuilder extends
      // @@protoc_insertion_point(interface_extends:googleprotobuf_json.CourseMarks)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 score = 2;</code>
     */
    boolean hasScore();
    /**
     * <code>optional int32 score = 2;</code>
     */
    int getScore();
  }
  /**
   * Protobuf type {@code googleprotobuf_json.CourseMarks}
   */
  public static final class CourseMarks extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:googleprotobuf_json.CourseMarks)
      CourseMarksOrBuilder {
    // Use CourseMarks.newBuilder() to construct.
    private CourseMarks(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CourseMarks(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CourseMarks defaultInstance;
    public static CourseMarks getDefaultInstance() {
      return defaultInstance;
    }

    public CourseMarks getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CourseMarks(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              score_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return googleprotobuf_json.ResultProto.internal_static_googleprotobuf_json_CourseMarks_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return googleprotobuf_json.ResultProto.internal_static_googleprotobuf_json_CourseMarks_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              googleprotobuf_json.ResultProto.CourseMarks.class, googleprotobuf_json.ResultProto.CourseMarks.Builder.class);
    }

    public static com.google.protobuf.Parser<CourseMarks> PARSER =
        new com.google.protobuf.AbstractParser<CourseMarks>() {
      public CourseMarks parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CourseMarks(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CourseMarks> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 2;
    private int score_;
    /**
     * <code>optional int32 score = 2;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 score = 2;</code>
     */
    public int getScore() {
      return score_;
    }

    private void initFields() {
      name_ = "";
      score_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, score_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, score_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static googleprotobuf_json.ResultProto.CourseMarks parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static googleprotobuf_json.ResultProto.CourseMarks parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static googleprotobuf_json.ResultProto.CourseMarks parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static googleprotobuf_json.ResultProto.CourseMarks parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static googleprotobuf_json.ResultProto.CourseMarks parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static googleprotobuf_json.ResultProto.CourseMarks parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static googleprotobuf_json.ResultProto.CourseMarks parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static googleprotobuf_json.ResultProto.CourseMarks parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static googleprotobuf_json.ResultProto.CourseMarks parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static googleprotobuf_json.ResultProto.CourseMarks parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(googleprotobuf_json.ResultProto.CourseMarks prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code googleprotobuf_json.CourseMarks}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:googleprotobuf_json.CourseMarks)
        googleprotobuf_json.ResultProto.CourseMarksOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return googleprotobuf_json.ResultProto.internal_static_googleprotobuf_json_CourseMarks_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return googleprotobuf_json.ResultProto.internal_static_googleprotobuf_json_CourseMarks_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                googleprotobuf_json.ResultProto.CourseMarks.class, googleprotobuf_json.ResultProto.CourseMarks.Builder.class);
      }

      // Construct using googleprotobuf_json.ResultProto.CourseMarks.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        score_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return googleprotobuf_json.ResultProto.internal_static_googleprotobuf_json_CourseMarks_descriptor;
      }

      public googleprotobuf_json.ResultProto.CourseMarks getDefaultInstanceForType() {
        return googleprotobuf_json.ResultProto.CourseMarks.getDefaultInstance();
      }

      public googleprotobuf_json.ResultProto.CourseMarks build() {
        googleprotobuf_json.ResultProto.CourseMarks result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public googleprotobuf_json.ResultProto.CourseMarks buildPartial() {
        googleprotobuf_json.ResultProto.CourseMarks result = new googleprotobuf_json.ResultProto.CourseMarks(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.score_ = score_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof googleprotobuf_json.ResultProto.CourseMarks) {
          return mergeFrom((googleprotobuf_json.ResultProto.CourseMarks)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(googleprotobuf_json.ResultProto.CourseMarks other) {
        if (other == googleprotobuf_json.ResultProto.CourseMarks.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        googleprotobuf_json.ResultProto.CourseMarks parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (googleprotobuf_json.ResultProto.CourseMarks) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int score_ ;
      /**
       * <code>optional int32 score = 2;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 score = 2;</code>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <code>optional int32 score = 2;</code>
       */
      public Builder setScore(int value) {
        bitField0_ |= 0x00000002;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 score = 2;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        score_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:googleprotobuf_json.CourseMarks)
    }

    static {
      defaultInstance = new CourseMarks(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:googleprotobuf_json.CourseMarks)
  }

  public interface StudentMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:googleprotobuf_json.StudentMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 rollNum = 2;</code>
     */
    boolean hasRollNum();
    /**
     * <code>optional int32 rollNum = 2;</code>
     */
    int getRollNum();

    /**
     * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
     */
    java.util.List<googleprotobuf_json.ResultProto.CourseMarks> 
        getMarksList();
    /**
     * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
     */
    googleprotobuf_json.ResultProto.CourseMarks getMarks(int index);
    /**
     * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
     */
    int getMarksCount();
    /**
     * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
     */
    java.util.List<? extends googleprotobuf_json.ResultProto.CourseMarksOrBuilder> 
        getMarksOrBuilderList();
    /**
     * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
     */
    googleprotobuf_json.ResultProto.CourseMarksOrBuilder getMarksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code googleprotobuf_json.StudentMsg}
   */
  public static final class StudentMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:googleprotobuf_json.StudentMsg)
      StudentMsgOrBuilder {
    // Use StudentMsg.newBuilder() to construct.
    private StudentMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StudentMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StudentMsg defaultInstance;
    public static StudentMsg getDefaultInstance() {
      return defaultInstance;
    }

    public StudentMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StudentMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              rollNum_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                marks_ = new java.util.ArrayList<googleprotobuf_json.ResultProto.CourseMarks>();
                mutable_bitField0_ |= 0x00000004;
              }
              marks_.add(input.readMessage(googleprotobuf_json.ResultProto.CourseMarks.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          marks_ = java.util.Collections.unmodifiableList(marks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return googleprotobuf_json.ResultProto.internal_static_googleprotobuf_json_StudentMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return googleprotobuf_json.ResultProto.internal_static_googleprotobuf_json_StudentMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              googleprotobuf_json.ResultProto.StudentMsg.class, googleprotobuf_json.ResultProto.StudentMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<StudentMsg> PARSER =
        new com.google.protobuf.AbstractParser<StudentMsg>() {
      public StudentMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StudentMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StudentMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROLLNUM_FIELD_NUMBER = 2;
    private int rollNum_;
    /**
     * <code>optional int32 rollNum = 2;</code>
     */
    public boolean hasRollNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 rollNum = 2;</code>
     */
    public int getRollNum() {
      return rollNum_;
    }

    public static final int MARKS_FIELD_NUMBER = 3;
    private java.util.List<googleprotobuf_json.ResultProto.CourseMarks> marks_;
    /**
     * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
     */
    public java.util.List<googleprotobuf_json.ResultProto.CourseMarks> getMarksList() {
      return marks_;
    }
    /**
     * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
     */
    public java.util.List<? extends googleprotobuf_json.ResultProto.CourseMarksOrBuilder> 
        getMarksOrBuilderList() {
      return marks_;
    }
    /**
     * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
     */
    public int getMarksCount() {
      return marks_.size();
    }
    /**
     * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
     */
    public googleprotobuf_json.ResultProto.CourseMarks getMarks(int index) {
      return marks_.get(index);
    }
    /**
     * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
     */
    public googleprotobuf_json.ResultProto.CourseMarksOrBuilder getMarksOrBuilder(
        int index) {
      return marks_.get(index);
    }

    private void initFields() {
      name_ = "";
      rollNum_ = 0;
      marks_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, rollNum_);
      }
      for (int i = 0; i < marks_.size(); i++) {
        output.writeMessage(3, marks_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, rollNum_);
      }
      for (int i = 0; i < marks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, marks_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static googleprotobuf_json.ResultProto.StudentMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static googleprotobuf_json.ResultProto.StudentMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static googleprotobuf_json.ResultProto.StudentMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static googleprotobuf_json.ResultProto.StudentMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static googleprotobuf_json.ResultProto.StudentMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static googleprotobuf_json.ResultProto.StudentMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static googleprotobuf_json.ResultProto.StudentMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static googleprotobuf_json.ResultProto.StudentMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static googleprotobuf_json.ResultProto.StudentMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static googleprotobuf_json.ResultProto.StudentMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(googleprotobuf_json.ResultProto.StudentMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code googleprotobuf_json.StudentMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:googleprotobuf_json.StudentMsg)
        googleprotobuf_json.ResultProto.StudentMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return googleprotobuf_json.ResultProto.internal_static_googleprotobuf_json_StudentMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return googleprotobuf_json.ResultProto.internal_static_googleprotobuf_json_StudentMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                googleprotobuf_json.ResultProto.StudentMsg.class, googleprotobuf_json.ResultProto.StudentMsg.Builder.class);
      }

      // Construct using googleprotobuf_json.ResultProto.StudentMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMarksFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        rollNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (marksBuilder_ == null) {
          marks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          marksBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return googleprotobuf_json.ResultProto.internal_static_googleprotobuf_json_StudentMsg_descriptor;
      }

      public googleprotobuf_json.ResultProto.StudentMsg getDefaultInstanceForType() {
        return googleprotobuf_json.ResultProto.StudentMsg.getDefaultInstance();
      }

      public googleprotobuf_json.ResultProto.StudentMsg build() {
        googleprotobuf_json.ResultProto.StudentMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public googleprotobuf_json.ResultProto.StudentMsg buildPartial() {
        googleprotobuf_json.ResultProto.StudentMsg result = new googleprotobuf_json.ResultProto.StudentMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rollNum_ = rollNum_;
        if (marksBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            marks_ = java.util.Collections.unmodifiableList(marks_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.marks_ = marks_;
        } else {
          result.marks_ = marksBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof googleprotobuf_json.ResultProto.StudentMsg) {
          return mergeFrom((googleprotobuf_json.ResultProto.StudentMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(googleprotobuf_json.ResultProto.StudentMsg other) {
        if (other == googleprotobuf_json.ResultProto.StudentMsg.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasRollNum()) {
          setRollNum(other.getRollNum());
        }
        if (marksBuilder_ == null) {
          if (!other.marks_.isEmpty()) {
            if (marks_.isEmpty()) {
              marks_ = other.marks_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureMarksIsMutable();
              marks_.addAll(other.marks_);
            }
            onChanged();
          }
        } else {
          if (!other.marks_.isEmpty()) {
            if (marksBuilder_.isEmpty()) {
              marksBuilder_.dispose();
              marksBuilder_ = null;
              marks_ = other.marks_;
              bitField0_ = (bitField0_ & ~0x00000004);
              marksBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMarksFieldBuilder() : null;
            } else {
              marksBuilder_.addAllMessages(other.marks_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        googleprotobuf_json.ResultProto.StudentMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (googleprotobuf_json.ResultProto.StudentMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int rollNum_ ;
      /**
       * <code>optional int32 rollNum = 2;</code>
       */
      public boolean hasRollNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 rollNum = 2;</code>
       */
      public int getRollNum() {
        return rollNum_;
      }
      /**
       * <code>optional int32 rollNum = 2;</code>
       */
      public Builder setRollNum(int value) {
        bitField0_ |= 0x00000002;
        rollNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rollNum = 2;</code>
       */
      public Builder clearRollNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rollNum_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<googleprotobuf_json.ResultProto.CourseMarks> marks_ =
        java.util.Collections.emptyList();
      private void ensureMarksIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          marks_ = new java.util.ArrayList<googleprotobuf_json.ResultProto.CourseMarks>(marks_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          googleprotobuf_json.ResultProto.CourseMarks, googleprotobuf_json.ResultProto.CourseMarks.Builder, googleprotobuf_json.ResultProto.CourseMarksOrBuilder> marksBuilder_;

      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public java.util.List<googleprotobuf_json.ResultProto.CourseMarks> getMarksList() {
        if (marksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(marks_);
        } else {
          return marksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public int getMarksCount() {
        if (marksBuilder_ == null) {
          return marks_.size();
        } else {
          return marksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public googleprotobuf_json.ResultProto.CourseMarks getMarks(int index) {
        if (marksBuilder_ == null) {
          return marks_.get(index);
        } else {
          return marksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public Builder setMarks(
          int index, googleprotobuf_json.ResultProto.CourseMarks value) {
        if (marksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMarksIsMutable();
          marks_.set(index, value);
          onChanged();
        } else {
          marksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public Builder setMarks(
          int index, googleprotobuf_json.ResultProto.CourseMarks.Builder builderForValue) {
        if (marksBuilder_ == null) {
          ensureMarksIsMutable();
          marks_.set(index, builderForValue.build());
          onChanged();
        } else {
          marksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public Builder addMarks(googleprotobuf_json.ResultProto.CourseMarks value) {
        if (marksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMarksIsMutable();
          marks_.add(value);
          onChanged();
        } else {
          marksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public Builder addMarks(
          int index, googleprotobuf_json.ResultProto.CourseMarks value) {
        if (marksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMarksIsMutable();
          marks_.add(index, value);
          onChanged();
        } else {
          marksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public Builder addMarks(
          googleprotobuf_json.ResultProto.CourseMarks.Builder builderForValue) {
        if (marksBuilder_ == null) {
          ensureMarksIsMutable();
          marks_.add(builderForValue.build());
          onChanged();
        } else {
          marksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public Builder addMarks(
          int index, googleprotobuf_json.ResultProto.CourseMarks.Builder builderForValue) {
        if (marksBuilder_ == null) {
          ensureMarksIsMutable();
          marks_.add(index, builderForValue.build());
          onChanged();
        } else {
          marksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public Builder addAllMarks(
          java.lang.Iterable<? extends googleprotobuf_json.ResultProto.CourseMarks> values) {
        if (marksBuilder_ == null) {
          ensureMarksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, marks_);
          onChanged();
        } else {
          marksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public Builder clearMarks() {
        if (marksBuilder_ == null) {
          marks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          marksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public Builder removeMarks(int index) {
        if (marksBuilder_ == null) {
          ensureMarksIsMutable();
          marks_.remove(index);
          onChanged();
        } else {
          marksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public googleprotobuf_json.ResultProto.CourseMarks.Builder getMarksBuilder(
          int index) {
        return getMarksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public googleprotobuf_json.ResultProto.CourseMarksOrBuilder getMarksOrBuilder(
          int index) {
        if (marksBuilder_ == null) {
          return marks_.get(index);  } else {
          return marksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public java.util.List<? extends googleprotobuf_json.ResultProto.CourseMarksOrBuilder> 
           getMarksOrBuilderList() {
        if (marksBuilder_ != null) {
          return marksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(marks_);
        }
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public googleprotobuf_json.ResultProto.CourseMarks.Builder addMarksBuilder() {
        return getMarksFieldBuilder().addBuilder(
            googleprotobuf_json.ResultProto.CourseMarks.getDefaultInstance());
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public googleprotobuf_json.ResultProto.CourseMarks.Builder addMarksBuilder(
          int index) {
        return getMarksFieldBuilder().addBuilder(
            index, googleprotobuf_json.ResultProto.CourseMarks.getDefaultInstance());
      }
      /**
       * <code>repeated .googleprotobuf_json.CourseMarks marks = 3;</code>
       */
      public java.util.List<googleprotobuf_json.ResultProto.CourseMarks.Builder> 
           getMarksBuilderList() {
        return getMarksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          googleprotobuf_json.ResultProto.CourseMarks, googleprotobuf_json.ResultProto.CourseMarks.Builder, googleprotobuf_json.ResultProto.CourseMarksOrBuilder> 
          getMarksFieldBuilder() {
        if (marksBuilder_ == null) {
          marksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              googleprotobuf_json.ResultProto.CourseMarks, googleprotobuf_json.ResultProto.CourseMarks.Builder, googleprotobuf_json.ResultProto.CourseMarksOrBuilder>(
                  marks_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          marks_ = null;
        }
        return marksBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:googleprotobuf_json.StudentMsg)
    }

    static {
      defaultInstance = new StudentMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:googleprotobuf_json.StudentMsg)
  }

  public interface ResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:googleprotobuf_json.Result)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
     */
    java.util.List<googleprotobuf_json.ResultProto.StudentMsg> 
        getStudentmsgList();
    /**
     * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
     */
    googleprotobuf_json.ResultProto.StudentMsg getStudentmsg(int index);
    /**
     * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
     */
    int getStudentmsgCount();
    /**
     * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
     */
    java.util.List<? extends googleprotobuf_json.ResultProto.StudentMsgOrBuilder> 
        getStudentmsgOrBuilderList();
    /**
     * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
     */
    googleprotobuf_json.ResultProto.StudentMsgOrBuilder getStudentmsgOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code googleprotobuf_json.Result}
   */
  public static final class Result extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:googleprotobuf_json.Result)
      ResultOrBuilder {
    // Use Result.newBuilder() to construct.
    private Result(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Result(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Result defaultInstance;
    public static Result getDefaultInstance() {
      return defaultInstance;
    }

    public Result getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                studentmsg_ = new java.util.ArrayList<googleprotobuf_json.ResultProto.StudentMsg>();
                mutable_bitField0_ |= 0x00000001;
              }
              studentmsg_.add(input.readMessage(googleprotobuf_json.ResultProto.StudentMsg.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          studentmsg_ = java.util.Collections.unmodifiableList(studentmsg_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return googleprotobuf_json.ResultProto.internal_static_googleprotobuf_json_Result_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return googleprotobuf_json.ResultProto.internal_static_googleprotobuf_json_Result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              googleprotobuf_json.ResultProto.Result.class, googleprotobuf_json.ResultProto.Result.Builder.class);
    }

    public static com.google.protobuf.Parser<Result> PARSER =
        new com.google.protobuf.AbstractParser<Result>() {
      public Result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Result(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Result> getParserForType() {
      return PARSER;
    }

    public static final int STUDENTMSG_FIELD_NUMBER = 1;
    private java.util.List<googleprotobuf_json.ResultProto.StudentMsg> studentmsg_;
    /**
     * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
     */
    public java.util.List<googleprotobuf_json.ResultProto.StudentMsg> getStudentmsgList() {
      return studentmsg_;
    }
    /**
     * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
     */
    public java.util.List<? extends googleprotobuf_json.ResultProto.StudentMsgOrBuilder> 
        getStudentmsgOrBuilderList() {
      return studentmsg_;
    }
    /**
     * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
     */
    public int getStudentmsgCount() {
      return studentmsg_.size();
    }
    /**
     * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
     */
    public googleprotobuf_json.ResultProto.StudentMsg getStudentmsg(int index) {
      return studentmsg_.get(index);
    }
    /**
     * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
     */
    public googleprotobuf_json.ResultProto.StudentMsgOrBuilder getStudentmsgOrBuilder(
        int index) {
      return studentmsg_.get(index);
    }

    private void initFields() {
      studentmsg_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < studentmsg_.size(); i++) {
        output.writeMessage(1, studentmsg_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < studentmsg_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, studentmsg_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static googleprotobuf_json.ResultProto.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static googleprotobuf_json.ResultProto.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static googleprotobuf_json.ResultProto.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static googleprotobuf_json.ResultProto.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static googleprotobuf_json.ResultProto.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static googleprotobuf_json.ResultProto.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static googleprotobuf_json.ResultProto.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static googleprotobuf_json.ResultProto.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static googleprotobuf_json.ResultProto.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static googleprotobuf_json.ResultProto.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(googleprotobuf_json.ResultProto.Result prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code googleprotobuf_json.Result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:googleprotobuf_json.Result)
        googleprotobuf_json.ResultProto.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return googleprotobuf_json.ResultProto.internal_static_googleprotobuf_json_Result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return googleprotobuf_json.ResultProto.internal_static_googleprotobuf_json_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                googleprotobuf_json.ResultProto.Result.class, googleprotobuf_json.ResultProto.Result.Builder.class);
      }

      // Construct using googleprotobuf_json.ResultProto.Result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStudentmsgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (studentmsgBuilder_ == null) {
          studentmsg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          studentmsgBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return googleprotobuf_json.ResultProto.internal_static_googleprotobuf_json_Result_descriptor;
      }

      public googleprotobuf_json.ResultProto.Result getDefaultInstanceForType() {
        return googleprotobuf_json.ResultProto.Result.getDefaultInstance();
      }

      public googleprotobuf_json.ResultProto.Result build() {
        googleprotobuf_json.ResultProto.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public googleprotobuf_json.ResultProto.Result buildPartial() {
        googleprotobuf_json.ResultProto.Result result = new googleprotobuf_json.ResultProto.Result(this);
        int from_bitField0_ = bitField0_;
        if (studentmsgBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            studentmsg_ = java.util.Collections.unmodifiableList(studentmsg_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.studentmsg_ = studentmsg_;
        } else {
          result.studentmsg_ = studentmsgBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof googleprotobuf_json.ResultProto.Result) {
          return mergeFrom((googleprotobuf_json.ResultProto.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(googleprotobuf_json.ResultProto.Result other) {
        if (other == googleprotobuf_json.ResultProto.Result.getDefaultInstance()) return this;
        if (studentmsgBuilder_ == null) {
          if (!other.studentmsg_.isEmpty()) {
            if (studentmsg_.isEmpty()) {
              studentmsg_ = other.studentmsg_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStudentmsgIsMutable();
              studentmsg_.addAll(other.studentmsg_);
            }
            onChanged();
          }
        } else {
          if (!other.studentmsg_.isEmpty()) {
            if (studentmsgBuilder_.isEmpty()) {
              studentmsgBuilder_.dispose();
              studentmsgBuilder_ = null;
              studentmsg_ = other.studentmsg_;
              bitField0_ = (bitField0_ & ~0x00000001);
              studentmsgBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getStudentmsgFieldBuilder() : null;
            } else {
              studentmsgBuilder_.addAllMessages(other.studentmsg_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        googleprotobuf_json.ResultProto.Result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (googleprotobuf_json.ResultProto.Result) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<googleprotobuf_json.ResultProto.StudentMsg> studentmsg_ =
        java.util.Collections.emptyList();
      private void ensureStudentmsgIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          studentmsg_ = new java.util.ArrayList<googleprotobuf_json.ResultProto.StudentMsg>(studentmsg_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          googleprotobuf_json.ResultProto.StudentMsg, googleprotobuf_json.ResultProto.StudentMsg.Builder, googleprotobuf_json.ResultProto.StudentMsgOrBuilder> studentmsgBuilder_;

      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public java.util.List<googleprotobuf_json.ResultProto.StudentMsg> getStudentmsgList() {
        if (studentmsgBuilder_ == null) {
          return java.util.Collections.unmodifiableList(studentmsg_);
        } else {
          return studentmsgBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public int getStudentmsgCount() {
        if (studentmsgBuilder_ == null) {
          return studentmsg_.size();
        } else {
          return studentmsgBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public googleprotobuf_json.ResultProto.StudentMsg getStudentmsg(int index) {
        if (studentmsgBuilder_ == null) {
          return studentmsg_.get(index);
        } else {
          return studentmsgBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public Builder setStudentmsg(
          int index, googleprotobuf_json.ResultProto.StudentMsg value) {
        if (studentmsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentmsgIsMutable();
          studentmsg_.set(index, value);
          onChanged();
        } else {
          studentmsgBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public Builder setStudentmsg(
          int index, googleprotobuf_json.ResultProto.StudentMsg.Builder builderForValue) {
        if (studentmsgBuilder_ == null) {
          ensureStudentmsgIsMutable();
          studentmsg_.set(index, builderForValue.build());
          onChanged();
        } else {
          studentmsgBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public Builder addStudentmsg(googleprotobuf_json.ResultProto.StudentMsg value) {
        if (studentmsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentmsgIsMutable();
          studentmsg_.add(value);
          onChanged();
        } else {
          studentmsgBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public Builder addStudentmsg(
          int index, googleprotobuf_json.ResultProto.StudentMsg value) {
        if (studentmsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentmsgIsMutable();
          studentmsg_.add(index, value);
          onChanged();
        } else {
          studentmsgBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public Builder addStudentmsg(
          googleprotobuf_json.ResultProto.StudentMsg.Builder builderForValue) {
        if (studentmsgBuilder_ == null) {
          ensureStudentmsgIsMutable();
          studentmsg_.add(builderForValue.build());
          onChanged();
        } else {
          studentmsgBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public Builder addStudentmsg(
          int index, googleprotobuf_json.ResultProto.StudentMsg.Builder builderForValue) {
        if (studentmsgBuilder_ == null) {
          ensureStudentmsgIsMutable();
          studentmsg_.add(index, builderForValue.build());
          onChanged();
        } else {
          studentmsgBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public Builder addAllStudentmsg(
          java.lang.Iterable<? extends googleprotobuf_json.ResultProto.StudentMsg> values) {
        if (studentmsgBuilder_ == null) {
          ensureStudentmsgIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, studentmsg_);
          onChanged();
        } else {
          studentmsgBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public Builder clearStudentmsg() {
        if (studentmsgBuilder_ == null) {
          studentmsg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          studentmsgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public Builder removeStudentmsg(int index) {
        if (studentmsgBuilder_ == null) {
          ensureStudentmsgIsMutable();
          studentmsg_.remove(index);
          onChanged();
        } else {
          studentmsgBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public googleprotobuf_json.ResultProto.StudentMsg.Builder getStudentmsgBuilder(
          int index) {
        return getStudentmsgFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public googleprotobuf_json.ResultProto.StudentMsgOrBuilder getStudentmsgOrBuilder(
          int index) {
        if (studentmsgBuilder_ == null) {
          return studentmsg_.get(index);  } else {
          return studentmsgBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public java.util.List<? extends googleprotobuf_json.ResultProto.StudentMsgOrBuilder> 
           getStudentmsgOrBuilderList() {
        if (studentmsgBuilder_ != null) {
          return studentmsgBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(studentmsg_);
        }
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public googleprotobuf_json.ResultProto.StudentMsg.Builder addStudentmsgBuilder() {
        return getStudentmsgFieldBuilder().addBuilder(
            googleprotobuf_json.ResultProto.StudentMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public googleprotobuf_json.ResultProto.StudentMsg.Builder addStudentmsgBuilder(
          int index) {
        return getStudentmsgFieldBuilder().addBuilder(
            index, googleprotobuf_json.ResultProto.StudentMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .googleprotobuf_json.StudentMsg studentmsg = 1;</code>
       */
      public java.util.List<googleprotobuf_json.ResultProto.StudentMsg.Builder> 
           getStudentmsgBuilderList() {
        return getStudentmsgFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          googleprotobuf_json.ResultProto.StudentMsg, googleprotobuf_json.ResultProto.StudentMsg.Builder, googleprotobuf_json.ResultProto.StudentMsgOrBuilder> 
          getStudentmsgFieldBuilder() {
        if (studentmsgBuilder_ == null) {
          studentmsgBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              googleprotobuf_json.ResultProto.StudentMsg, googleprotobuf_json.ResultProto.StudentMsg.Builder, googleprotobuf_json.ResultProto.StudentMsgOrBuilder>(
                  studentmsg_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          studentmsg_ = null;
        }
        return studentmsgBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:googleprotobuf_json.Result)
    }

    static {
      defaultInstance = new Result(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:googleprotobuf_json.Result)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_googleprotobuf_json_CourseMarks_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_googleprotobuf_json_CourseMarks_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_googleprotobuf_json_StudentMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_googleprotobuf_json_StudentMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_googleprotobuf_json_Result_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_googleprotobuf_json_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Result.proto\022\023googleprotobuf_json\"*\n\013C" +
      "ourseMarks\022\014\n\004name\030\001 \001(\t\022\r\n\005score\030\002 \001(\005\"" +
      "\\\n\nStudentMsg\022\014\n\004name\030\001 \001(\t\022\017\n\007rollNum\030\002" +
      " \001(\005\022/\n\005marks\030\003 \003(\0132 .googleprotobuf_jso" +
      "n.CourseMarks\"=\n\006Result\0223\n\nstudentmsg\030\001 " +
      "\003(\0132\037.googleprotobuf_json.StudentMsgB\rB\013" +
      "ResultProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_googleprotobuf_json_CourseMarks_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_googleprotobuf_json_CourseMarks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_googleprotobuf_json_CourseMarks_descriptor,
        new java.lang.String[] { "Name", "Score", });
    internal_static_googleprotobuf_json_StudentMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_googleprotobuf_json_StudentMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_googleprotobuf_json_StudentMsg_descriptor,
        new java.lang.String[] { "Name", "RollNum", "Marks", });
    internal_static_googleprotobuf_json_Result_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_googleprotobuf_json_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_googleprotobuf_json_Result_descriptor,
        new java.lang.String[] { "Studentmsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
